sudo: false
language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"

cache:
  directories:
    - $HOME/virtualenv/python3.8/
    - $HOME/virtualenv/python3.7/
    - $HOME/virtualenv/python3.6/

jobs:
  include:
    - stage: tests
      script: tox

    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: serenata
        password: $PYPI_PASSWORD
        distributions: "sdist bdist_wheel"
        on:
          branch: master

install:
  - python -m pip install -U coveralls coverage tox-travis
  - python -m pip install -U -e .
  - coverage erase

after_success:
  - coverage combine
  - coverage report
  - coveralls
